language: python
python:
- '2.7'
env:
  - TEST_DIR=package
  - TEST_DIR=huawei_vrp_shell

install:
    pushd package
    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
        python setup.py develop --no-deps;
      else
        # todo: fix dependencies mismatch and use python setup.py install instead
        pip install -r requirements.txt;
        python setup.py develop --no-deps;
      fi'
    popd
    - cd $TEST_DIR
    - pip install -r test_requirements.txt

script:
    - 'if [ $TEST_DIR = "package" ]; then
        nosetests --with-coverage --cover-package=cloudshell.networking.huawei.vrp tests;
      else
        nosetests --with-coverage --cover-package=src tests;
      fi'

after_success:
    - coveralls