language: python
python:
    - "2.7"

install:
    # todo: fix dependencies mismatch and use python setup.py install instead
    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f dev_requirements.txt ]; then
        pushd package;
        pip install -r dev_requirements.txt;
        python setup.py develop --no-deps;
        popd;
      else
        pushd package;
        pip install -r requirements.txt;
        python setup.py develop --no-deps;
        popd;
      fi'
    - pip install -r huawei_vrp_shell/src/requirements.txt
    - pip install -r package/test_requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=src,cloudshell.networking.huawei.vrp package/tests huawei_vrp_shell/tests

after_success:
    - coveralls